spring.application.name=EmployeeManagementSystem
#URL
spring.datasource.url=jdbc:postgresql://dpg-d57ght63jp1c73avduvg-a.frankfurt-postgres.render.com:5432/ems_ht8s?sslmode=require
#Username
spring.datasource.username=ems_ht8s_user
#Password
spring.datasource.password=MESwmK9DsV1gyVQhxzaYbh5uSgNTXJcm
# Driver PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# ---  JPA / HIBERNATE ---

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true